### ISSUE TITLE
[정기 세션] 8차 세션 백엔드 to-do list

### ISSUE THREAD

**Issue by ybell1028** [YAPP-18th/Web-Team-1-Backend#6]
- [x] 댓글 테이블 설계
- [x] **Jenkins 프리티어 내에서 돌려보도록 노력**
- [x] EC2 하나 더 만들어보기
- [x] API 규칙 간단하게 짜기 + 문서화
- [x] API 명세서 수정 1차
